import { Property } from '../../types';

export const MOCK_PROPERTIES: Property[] = [
  {
    id: '1',
    title: 'Modern Studio Near University of Lagos',
    description: 'Cozy studio apartment perfect for students. Fully furnished with all amenities included.',
    price: 250000,
    location: 'Yaba, Lagos',
    address: '123 University Road',
    bedrooms: 1,
    bathrooms: 1,
    size: 35,
    amenities: ['Wi-Fi', 'Air Conditioning', 'Security', 'Water Supply'],
    images: ['https://images.pexels.com/photos/1918291/pexels-photo-1918291.jpeg'],
    landlordId: 'landlord1',
    createdAt: '2023-09-15T00:00:00Z',
    updatedAt: '2023-09-15T00:00:00Z',
    available: true,
    featured: true
  },
  {
    id: '2',
    title: '2 Bedroom Apartment Near Covenant University',
    description: 'Spacious 2 bedroom apartment ideal for sharing. Close to campus with excellent amenities.',
    price: 450000,
    location: 'Ota, Ogun',
    address: '45 Covenant Drive',
    bedrooms: 2,
    bathrooms: 1,
    size: 60,
    amenities: ['Wi-Fi', 'Generator', 'Security', 'Parking'],
    images: ['https://images.pexels.com/photos/1643384/pexels-photo-1643384.jpeg'],
    landlordId: 'landlord2',
    createdAt: '2023-10-05T00:00:00Z',
    updatedAt: '2023-10-05T00:00:00Z',
    available: true,
    featured: false
  },
  {
    id: '3',
    title: 'Luxury 3 Bedroom Flat Near UniAbuja',
    description: 'Premium 3 bedroom flat in a gated community. Perfect for students looking for a comfortable living space.',
    price: 650000,
    location: 'Abuja, FCT',
    address: '78 University Way',
    bedrooms: 3,
    bathrooms: 2,
    size: 85,
    amenities: ['Wi-Fi', 'Swimming Pool', '24/7 Security', 'Generator'],
    images: ['https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg'],
    landlordId: 'landlord3',
    createdAt: '2023-11-20T00:00:00Z',
    updatedAt: '2023-11-20T00:00:00Z',
    available: true,
    featured: true
  },
  {
    id: '4',
    title: 'Single Room Self Contain Near UI',
    description: 'Affordable single room self-contained accommodation near University of Ibadan. Ideal for students on a budget.',
    price: 180000,
    location: 'Ibadan, Oyo',
    address: '15 Agbowo Street',
    bedrooms: 1,
    bathrooms: 1,
    size: 25,
    amenities: ['Water Supply', 'Shared Generator', 'Security'],
    images: ['https://images.pexels.com/photos/271624/pexels-photo-271624.jpeg'],
    landlordId: 'landlord4',
    createdAt: '2023-12-10T00:00:00Z',
    updatedAt: '2023-12-10T00:00:00Z',
    available: true,
    featured: false
  },
  {
    id: '5',
    title: 'Shared 4 Bedroom Apartment Near OAU',
    description: 'Large 4 bedroom apartment perfect for sharing. Located within walking distance to OAU campus.',
    price: 150000,
    location: 'Ile-Ife, Osun',
    address: '33 Ede Road',
    bedrooms: 4,
    bathrooms: 2,
    size: 100,
    amenities: ['Wi-Fi', 'Furniture', 'Kitchen', 'Balcony'],
    images: ['https://images.pexels.com/photos/1457842/pexels-photo-1457842.jpeg'],
    landlordId: 'landlord5',
    createdAt: '2024-01-15T00:00:00Z',
    updatedAt: '2024-01-15T00:00:00Z',
    available: true,
    featured: false
  },
  {
    id: '6',
    title: 'Modern 2 Bedroom Flat Near UNIPORT',
    description: 'Recently renovated 2 bedroom flat with modern amenities. Close to University of Port Harcourt.',
    price: 400000,
    location: 'Port Harcourt, Rivers',
    address: '12 Choba Road',
    bedrooms: 2,
    bathrooms: 1,
    size: 55,
    amenities: ['Wi-Fi', 'Air Conditioning', 'Security', 'Generator'],
    images: ['https://images.pexels.com/photos/276724/pexels-photo-276724.jpeg'],
    landlordId: 'landlord6',
    createdAt: '2024-02-08T00:00:00Z',
    updatedAt: '2024-02-08T00:00:00Z',
    available: true,
    featured: true
  }
];